//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenericMathematics {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenericMathematics.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a, b must be &gt; 0..
        /// </summary>
        internal static string Algorithms_ABMustBeGreaterZero {
            get {
                return ResourceManager.GetString("Algorithms_ABMustBeGreaterZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Need at least one value to calculate LCM..
        /// </summary>
        internal static string Algorithms_NeedArgumentLcm {
            get {
                return ResourceManager.GetString("Algorithms_NeedArgumentLcm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на T must be integer type..
        /// </summary>
        internal static string Algorithms_TypeMustBeInteger {
            get {
                return ResourceManager.GetString("Algorithms_TypeMustBeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Power degree must be &gt;= 0..
        /// </summary>
        internal static string Complex_PowerDegree {
            get {
                return ResourceManager.GetString("Complex_PowerDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Root&apos;s degree must be &gt;= 2..
        /// </summary>
        internal static string Complex_RootDegree {
            get {
                return ResourceManager.GetString("Complex_RootDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на format must be non empty..
        /// </summary>
        internal static string FormatParser_FormatIsEmpty {
            get {
                return ResourceManager.GetString("FormatParser_FormatIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на T need to implement IFormattable..
        /// </summary>
        internal static string GenericType_NotIFormattable {
            get {
                return ResourceManager.GetString("GenericType_NotIFormattable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not find a math implementation for element type &apos;{0}&apos;..
        /// </summary>
        internal static string Math_ImplementationNotFound {
            get {
                return ResourceManager.GetString("Math_ImplementationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User-defined math type &apos;{0}&apos; for element type &apos;{1}&apos; doesn&apos;t derive Math`1..
        /// </summary>
        internal static string Math_InvalidUserDefinition {
            get {
                return ResourceManager.GetString("Math_InvalidUserDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Column must be &gt; 0 and &lt; matrix.Columns..
        /// </summary>
        internal static string Matrix_ColumnMustBeInRangle {
            get {
                return ResourceManager.GetString("Matrix_ColumnMustBeInRangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на values.Length must be equal to (rows * columns)..
        /// </summary>
        internal static string Matrix_LengthEqualsRowsColumns {
            get {
                return ResourceManager.GetString("Matrix_LengthEqualsRowsColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на m.Rows must be equal to m.Columns..
        /// </summary>
        internal static string Matrix_MustBeSquareMatrix {
            get {
                return ResourceManager.GetString("Matrix_MustBeSquareMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Row must be &gt; 0 and &lt; matrix.Rows.
        /// </summary>
        internal static string Matrix_RowMustBeInRangle {
            get {
                return ResourceManager.GetString("Matrix_RowMustBeInRangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на matrix1.{0} must be equal to matrix2.{1}..
        /// </summary>
        internal static string Matrix_RowsOrColumnsEqual {
            get {
                return ResourceManager.GetString("Matrix_RowsOrColumnsEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Matrix size must be &gt; 1..
        /// </summary>
        internal static string Matrix_SizeMustBeMoreOne {
            get {
                return ResourceManager.GetString("Matrix_SizeMustBeMoreOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Matrix size must be &gt; 0..
        /// </summary>
        internal static string Matrix_SizeMustBeMoreZero {
            get {
                return ResourceManager.GetString("Matrix_SizeMustBeMoreZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sizes of matrix1 and matrix2 must be equal..
        /// </summary>
        internal static string Matrix_SizesMustBeEqual {
            get {
                return ResourceManager.GetString("Matrix_SizesMustBeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type of value must be {0}..
        /// </summary>
        internal static string TypeConverter_ValueTypeMismatch {
            get {
                return ResourceManager.GetString("TypeConverter_ValueTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Conversation from {0} to {1} is not supported..
        /// </summary>
        internal static string ValueConverter_NotSupported {
            get {
                return ResourceManager.GetString("ValueConverter_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transformation matrix rows and columns must be equal 4..
        /// </summary>
        internal static string Vector_Transform3DMatrixSize {
            get {
                return ResourceManager.GetString("Vector_Transform3DMatrixSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transformation matrix rows and columns must be &gt;= 2..
        /// </summary>
        internal static string Vector2_TransformNormalMatrixSize {
            get {
                return ResourceManager.GetString("Vector2_TransformNormalMatrixSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transformation matrix rows and columns must be &gt;= 3..
        /// </summary>
        internal static string Vector3_TransformNormalMatrixSize {
            get {
                return ResourceManager.GetString("Vector3_TransformNormalMatrixSize", resourceCulture);
            }
        }
    }
}
